[build]
  publish = "eshyttekom_nettside"
  functions = "netlify/functions"

[dev]
  publish = "eshyttekom_nettside"
  functions = "netlify/functions"

[context.production.environment]
  SUPABASE_URL = ""
  SUPABASE_SERVICE_KEY = ""
  SUPABASE_BOOKING_TABLE = "bookinger"
  GMAIL_USER = "noreplyeshyttekom@gmail.com"
  GMAIL_APP_PASSWORD = ""
  
  

[context.deploy-preview.environment]
  SUPABASE_URL = ""
  SUPABASE_SERVICE_KEY = ""
  SUPABASE_BOOKING_TABLE = "bookinger"
  GMAIL_USER = "noreplyeshyttekom@gmail.com"
  GMAIL_APP_PASSWORD = ""

[context.branch-deploy.environment]
  SUPABASE_URL = ""
  SUPABASE_SERVICE_KEY = ""
  SUPABASE_BOOKING_TABLE = "bookinger"
  GMAIL_USER = "noreplyeshyttekom@gmail.com"
  GMAIL_APP_PASSWORD = ""